name: CI

on:
 workflow_dispatch:
 
jobs:
  install-prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt-get install wget
          sudo apt-get install fontconfig

  download-and-install-readyapi:
    runs-on: ubuntu-latest
    needs: install-prerequisites
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download ReadyAPI
        run: |
          wget "https://dl.eviware.com/ready-api/3.53.0/ReadyAPI-x64-3.53.0.sh"

      - name: Make file executable
        run: chmod +x ${{ github.workspace }}/ReadyAPI-x64-3.53.0.sh

      - name: Install ReadyAPI
        run: sudo sh ${{ github.workspace }}/ReadyAPI-x64-3.53.0.sh -q

      - name: Run Tests
        run: sudo sh /opt/SmartBear/ReadyAPI-3.53.0/bin/testrunner.sh -r -a -j -f${{ github.workspace }} "-RJUnit-Style HTML Report" -FXML "-EDefault environment" -accessKey ${{ secrets.SLM_ACCESSKEY }} ${{ github.workspace }}/PetStoreForAzurePipeline-readyapi-project.xml
